In [1]:
import torch.nn as nn
import torch.nn.functional as F
import torch
import numpy as np
import torch.optim as optim

In [2]:
file = open("C:/Users/kshitij/Desktop/NLP/DinoName/names.txt")
names = file.read().split('\n')

for i in range(len(names)):
    names[i]=names[i].lower()
#     names[i]+='.'

names

['aachenosaurus',
 'aardonyx',
 'abdallahsaurus',
 'abelisaurus',
 'abrictosaurus',
 'abrosaurus',
 'abydosaurus',
 'acanthopholis',
 'achelousaurus',
 'acheroraptor',
 'achillesaurus',
 'achillobator',
 'acristavus',
 'acrocanthosaurus',
 'acrotholus',
 'actiosaurus',
 'adamantisaurus',
 'adasaurus',
 'adelolophus',
 'adeopapposaurus',
 'aegyptosaurus',
 'aeolosaurus',
 'aepisaurus',
 'aepyornithomimus',
 'aerosteon',
 'aetonyxafromimus',
 'afrovenator',
 'agathaumas',
 'aggiosaurus',
 'agilisaurus',
 'agnosphitys',
 'agrosaurus',
 'agujaceratops',
 'agustinia',
 'ahshislepelta',
 'airakoraptor',
 'ajancingenia',
 'ajkaceratops',
 'alamosaurus',
 'alaskacephale',
 'albalophosaurus',
 'albertaceratops',
 'albertadromeus',
 'albertavenator',
 'albertonykus',
 'albertosaurus',
 'albinykus',
 'albisaurus',
 'alcovasaurus',
 'alectrosaurus',
 'aletopelta',
 'algoasaurus',
 'alioramus',
 'aliwalia',
 'allosaurus',
 'almas',
 'alnashetri',
 'alocodon',
 'altirhinus',
 'altispinax',
 'alvarez

In [3]:
alphabets = ['.','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
one = list(np.zeros((len(alphabets))))
alpha_dict={}
for n,i in enumerate(alphabets):
    one[n]=1
    alpha_dict[i] = one
    one = list(np.zeros((len(alphabets))))
print(alpha_dict)

{'.': [1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'a': [0.0, 1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'b': [0.0, 0.0, 1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'c': [0.0, 0.0, 0.0, 1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'd': [0.0, 0.0, 0.0, 0.0, 1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'e': [0.0, 0.0, 0.0, 0.0, 0.0, 1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'f': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'g': [0.0, 0.0, 0.0

In [4]:
#name_one_hot_encodings
name_list = []
for i in names:
    name_encoding = []
    for j in i:
        name_encoding.append(alpha_dict[j])
    name_list.append(name_encoding)
        
for i in range(len(name_list)):
    name_list[i]=torch.Tensor(name_list[i])

In [19]:
for i in range(100):
    print(target_list[i])

tensor([ 1,  3,  8,  5, 14, 15, 19,  1, 21, 18, 21, 19,  0])
tensor([ 1, 18,  4, 15, 14, 25, 24,  0])
tensor([ 2,  4,  1, 12, 12,  1,  8, 19,  1, 21, 18, 21, 19,  0])
tensor([ 2,  5, 12,  9, 19,  1, 21, 18, 21, 19,  0])
tensor([ 2, 18,  9,  3, 20, 15, 19,  1, 21, 18, 21, 19,  0])
tensor([ 2, 18, 15, 19,  1, 21, 18, 21, 19,  0])
tensor([ 2, 25,  4, 15, 19,  1, 21, 18, 21, 19,  0])
tensor([ 3,  1, 14, 20,  8, 15, 16,  8, 15, 12,  9, 19,  0])
tensor([ 3,  8,  5, 12, 15, 21, 19,  1, 21, 18, 21, 19,  0])
tensor([ 3,  8,  5, 18, 15, 18,  1, 16, 20, 15, 18,  0])
tensor([ 3,  8,  9, 12, 12,  5, 19,  1, 21, 18, 21, 19,  0])
tensor([ 3,  8,  9, 12, 12, 15,  2,  1, 20, 15, 18,  0])
tensor([ 3, 18,  9, 19, 20,  1, 22, 21, 19,  0])
tensor([ 3, 18, 15,  3,  1, 14, 20,  8, 15, 19,  1, 21, 18, 21, 19,  0])
tensor([ 3, 18, 15, 20,  8, 15, 12, 21, 19,  0])
tensor([ 3, 20,  9, 15, 19,  1, 21, 18, 21, 19,  0])
tensor([ 4,  1, 13,  1, 14, 20,  9, 19,  1, 21, 18, 21, 19,  0])
tensor([ 4,  1, 19,  1, 21, 18,

In [6]:
file = open("C:/Users/kshitij/Desktop/NLP/DinoName/names.txt")
names = file.read().split('\n')

for i in range(len(names)):
    names[i]=names[i].lower()
    names[i]+='.'
print(names)

['aachenosaurus.', 'aardonyx.', 'abdallahsaurus.', 'abelisaurus.', 'abrictosaurus.', 'abrosaurus.', 'abydosaurus.', 'acanthopholis.', 'achelousaurus.', 'acheroraptor.', 'achillesaurus.', 'achillobator.', 'acristavus.', 'acrocanthosaurus.', 'acrotholus.', 'actiosaurus.', 'adamantisaurus.', 'adasaurus.', 'adelolophus.', 'adeopapposaurus.', 'aegyptosaurus.', 'aeolosaurus.', 'aepisaurus.', 'aepyornithomimus.', 'aerosteon.', 'aetonyxafromimus.', 'afrovenator.', 'agathaumas.', 'aggiosaurus.', 'agilisaurus.', 'agnosphitys.', 'agrosaurus.', 'agujaceratops.', 'agustinia.', 'ahshislepelta.', 'airakoraptor.', 'ajancingenia.', 'ajkaceratops.', 'alamosaurus.', 'alaskacephale.', 'albalophosaurus.', 'albertaceratops.', 'albertadromeus.', 'albertavenator.', 'albertonykus.', 'albertosaurus.', 'albinykus.', 'albisaurus.', 'alcovasaurus.', 'alectrosaurus.', 'aletopelta.', 'algoasaurus.', 'alioramus.', 'aliwalia.', 'allosaurus.', 'almas.', 'alnashetri.', 'alocodon.', 'altirhinus.', 'altispinax.', 'alvarez

In [7]:
#target_encodings
alpha = {'a':1,'b':2,'c':3,'d':4,'e':5,'f':6,'g':7,'h':8,'i':9,'j':10,'k':11,'l':12,'m':13,'n':14,'o':15,'p':16,'q':17,'r':18,'s':19,'t':20,'u':21,'v':22,'w':23,'x':24,'y':25,'z':26,'.':0}
target_list = []
for i in names:
    target_encoding = []
    for j in i[1:]:
        target_encoding.append(alpha[j])
    target_list.append(target_encoding)

for i in range(len(target_list)):
    target_list[i]=torch.Tensor(target_list[i]).long()

In [8]:
print(target_list[0])

tensor([ 1,  3,  8,  5, 14, 15, 19,  1, 21, 18, 21, 19,  0])


In [81]:
class RNN(nn.Module):
    def __init__(self, inputsize, hiddensize, outputsize):
        super().__init__()
        self.hiddensize = hiddensize
        self.rnn = nn.RNN(inputsize, hiddensize, batch_first=True,bidirectional=True)
        self.fc = nn.Linear(hiddensize*2, outputsize)
    def forward(self, x, h):
        output,hidden = self.rnn(x,h)
        output = torch.tanh(output)
        output = self.fc(output)
        return output,hidden
    def initHidden(self):
        return torch.zeros([2,1,self.hiddensize])

In [89]:
input_size = 27
hidden_size = 25
output_size = 27
learning_rate = 0.001
model = RNN(27,50,27)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr=learning_rate)
print(model)

RNN(
  (rnn): RNN(27, 50, batch_first=True, bidirectional=True)
  (fc): Linear(in_features=100, out_features=27, bias=True)
)


In [90]:
for epochs in range(3):
    e=0
    for i in range(len(name_list)):
        optimizer.zero_grad()
        model.zero_grad()
        h = model.initHidden()
        x = name_list[i]
        x = x.unsqueeze(0)
        y = target_list[i]
        out,_ = model.forward(x,h)
        out = out.view(-1,output_size)
        loss = criterion(out, y)
        loss.backward()
        e+=loss.item()
        optimizer.step()
    print(epochs+1,' : ',e/len(name_list))

1  :  0.7437418356639682
2  :  0.06097264473191899
3  :  0.01748159053533982


In [91]:
alpha = {'a':1,'b':2,'c':3,'d':4,'e':5,'f':6,'g':7,'h':8,'i':9,'j':10,'k':11,'l':12,'m':13,'n':14,'o':15,'p':16,'q':17,'r':18,'s':19,'t':20,'u':21,'v':22,'w':23,'x':24,'y':25,'z':26,'.':0}
letter = ['.','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
digits = list(alpha.values())
with torch.no_grad():
    for n,i in enumerate(alpha_dict):
        h,c = model.initHidden()
        print()
        lis=[]
        lis.append(n)
        x = torch.Tensor(alpha_dict[i])
        x = x.view(1,1,-1)
        output,state = model.forward(x,(h,c))
        h, c = state
        output = F.softmax(output,dim=2)
        et = torch.argmax(output)
#         print(et)
        x = torch.zeros(x.shape)
        x[0,0,et] = 1
        while et!=0:
            output,state = model.forward(x,h,c)
            h,c = state
            output = F.softmax(output,dim=2)
            et = torch.argmax(output)
            x = torch.zeros(x.shape)
            x[0,0,et] = 1
            lis.append(et)
#         print(lis)
        for k in lis:
            print(letter[k],end='')
        


.
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z

In [87]:
lis

[26]

In [53]:

m = nn.Softmax(dim=2)
for n,i in enumerate(alpha_dict):
    if n==0:
        pass
    else:
        print(i,' for: ',end='')
        cap = True
        lis=[]
        lis.append(n)
        simp = torch.Tensor(alpha_dict[i]).view(1,1,-1)
        count = 0
        while cap:
            if count==0:
                pred = model.forward(simp,h)
                ans = m(pred)
            else:
                pred = model.forward(ans,h)
                ans = m(pred)
            count+=1
            lis.append(torch.argmax(ans).item())
    #         print(torch.argmax(ans))
        #     break
            if torch.argmax(ans) == 26:
                cap=False
        nums = np.arange(0,27)
        al = ['.','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
        for j in lis:
            print(al[j],end="")
        print()



a  for: 

AttributeError: 'tuple' object has no attribute 'softmax'

In [24]:
torch.save(model.state_dict(),'C:/Users/kshitij/Desktop/NLP/dino_names_using_inbuilt_rnn.pth')